import React, {useState, useEffect, useRef, Component} from 'react';
import logo from './logo.svg';
import './App.css';
// import ScrollButton from 'react-scroll-button'

// class ScrollComponent extends Component {
//   render() {
//       return (
//           <ScrollButton 
//               behavior={'smooth'} 
//               buttonBackgroundColor={'red'}
//               iconType={'arrow-up'}
//               style= {{fontSize: '24px'}}
//           />
//       );
//   }
// }
let mainContent = ["https://www.youtube.com/embed/onvlPpOiNsY?autoplay=1&lpp=1&autopause=0" ]
function App() {
  return (
  <div>
  <Main/>
  </div>
  );
} 

function Main(props) {
  return (

<div id= "titlestuff"> 

<div className='main'>
<h1><strong>Interdisciplinary Analysis of Tech Companies in Cities</strong> </h1>

<div id="titlelines"><strong><p id="titleline"> By Greta Solomon </p> </strong></div>
</div>


<div className="firstline">
      <button id="Intro" onClick>Intro</button>



      <button id="Background" onClick>Background</button>
      <button id="Litreview" onClick>Literature</button>
      <button id="Method" onClick>Method</button>
      </div>
      <div className="secondline">
      <button id="Analysis" onClick>Analysis</button>
      <button id="Futureplans" onClick>Future </button>
      <button id="Conclusions" onClick>Conclusions </button>
      <button id="References" onClick>Bibliography </button>
    </div>
<br></br>

<div class="videos">
<div id="video"><iframe iframe="true" src={mainContent[0]} iframe width="560" height="315" frameborder="0" allow="autoplay" allow="fullscreen" mute="true" loop="true"></iframe> </div>
</div>

<div className="sections">

  <div id="intro">
  <p>Project Statement</p><br></br><p>

In August of 2018 I was at a blockchain conference in Berlin. Cryptographers, technologists, and tech entrepreneurs speculated about methods of implementation of blockchain technology if the token economy were to scale beyond its current, mainly private state. I was immediately caught off guard by the missing actors in the conversation. This discussion was largely about governance, mass education, ethics, and public infrastructure implementation methodology. Where were the political scientists and theorists, philosophers, educators, and experts that study the information and theories people have been writing about and recording on these subjects for thousands of years? I soon realized this question did not only apply to the blockchain conversation, but to a lot of modern technologies entering public spaces. I decided to focus on one of the most interdisciplinary conversations, relevant to my urban studies background, of technology companies moving into cities from the perspective of urban studies and from the perspective of the technology companies and computer scientists. 
<br></br><br></br>This project evaluates whether technology, specifically text analysis, can identify opportunities for collaboration in sustainable urban problem solving. To begin to answer this question, I ask if text as data analysis can be used to offer clear aid in communicating between the fields of urban planning and technology when discussing the subject of technology companies physically moving into cities whether that be headquarters, research and development centers, or general technology clusters. To test this, I apply a text analysis using Atlas.ti to four
 urban studies articles and four technology review articles discussing the locations for the headquarters, R&D centers, and tech clusters of large technology corporations. In order to conduct my method of text scraping, my literature review will combine both works on cross discipline collaboration, a review of key literature on location scouting for big technology firms, as well as a review of similar case studies of text and sentiment analysis. 
 </p>
  </div>
  <div id="background">
    <p>Background</p><br></br>
    <img src= "https://i.ibb.co/xs8B5Rj/JMJ3998.jpg" height = "400" width = "300" />
<p>The response I received from the academics regarding blockchain prompted me to begin to question the mechanisms working for and against collaboration and communication between different types of information and disciplines.
<br></br><br></br>These questions now underpin this capstone project. First, these questions led to researching the relationship between collective intelligence and artificial intelligence technologies at Governance Lab, a research institute studying how to increase legitimate and effective governing through technology, in a summer position. It became evident that many public, typically government-led projects that use modern technology, such as more advanced machine learning (i.e deep learning), tebd to aggregate, sort, visualize, and generally process the information gathered from large groups of people. In a lot of cases, governments find more complicated technology to be less permeable in terms of understanding and implementing them publicly, than older forms of data analysis such as electronic surveys and other data analytics tools. City governments often partner with technology companies to use these data analysis tools to sort citizens’ comments. Localities collect citizens’ thoughts and concerns regarding subjects such as a large tech company moving into their city. After collecting and sorting feedback,  sentiment analysis is then used and presented as data for political leaders to optionally use in their policy proposals. 
<br></br><br></br>While collective intelligence can be facilitated through technology for democratic public policy in cities, the concept can also be valuably applied to the privacy sector’s role in cities. “Smart cities” have been popping up with investments from large companies like IBM and Cisco since the late twentieth century. In addition, large technology company headquarters such as Amazon in New York City caused so much public distress that protests ended in Amazon finding a new headquarter location. After discussing with a local historian and author of A Brief History of Saugerties, Michael Sullivan Smith, in Saugerties, New York about how IBM had “destroyed” their town back in the 1990’s, it became clear that there is ongoing, severe tension between the tech sector and the public, and thus the urban planning and development sector that works to create better cities for the people that live in them. What if there was a way to see if, beyond collective intelligence of sentiment analysis of the public, data analysis tools could be used to create better communication between public and private stakeholders directly involved with technology companies moving into cities. 
</p>
  </div>
  <div id="lit">
  <p>Literature Review</p>
  <img src= "https://i.ibb.co/ZSNMRpB/JMJ4025.jpg" height = "300" width = "500" />
  <p><br></br><br></br>Approaching Interdisciplinarity 
	<br></br><br></br>For the purpose of this research, it is important to start by defining interdisciplinarity and the current makeup of how it operates in order to test and analyze a method of proposing collaboration. The “Logics of Interdisciplinarity” in the Economy and Society journal is one jumping off point for this investigation. Writer Andrew Barry, a Professor in the Department of Geography at the University College of London, has a background in science and technology studies and has conducted research related to IT, pharmaceuticals, oil industries, and environmental and technological politics. At the Oxford University Centre for the Environment, Barry worked with Cambridge University Professor Georgina Born, as well as Research Associate Gisa Weszkalnys to conduct research on the “Logic of Interdisciplinarity”. They argue that instead of interdisciplinarity as the addition of two or more disciplines, there are two modes of modern interdisciplinarity, “Integrative-synthesis” and “subordination-service”. “Integrative-synthesis” hopes to facilitate “epistemic change”. This kind of synthesis takes a more incorporative approach, rather than the commonly thought of “interdisciplinarity” that tends to be more additive. It is unclear where the line is then drawn for transdisciplinarity. The authors explain “Subordination-service” as the arts and social sciences reinforcing the natural science and engineering work and vice versa. The examination of key vocabulary used in the ten journal articles later on in the method and analysis sections aims to apply a combination of both interdisciplinarity concepts. On one hand, “integrative-synthesis” interdisciplinarity in identifying key areas of divergence as well as the “subordination-service” through the overarching goal of both disciplines to improve their field, whether that be technological innovations or more livable cities. 
  <br></br><br></br>Additionally, Professor of the History of Science and of Physics Peter Galison, and Professor of Philosophy David Stump offer another layer of interdisciplinarity in science in their book, The Disunity of Science: Boundaries, Contexts, and Power. They argue that, “By shifting our attention away from the process of choosing between competing theories to the processes that allow a group to maintain cohesion, build a common socio-disciplinary identity, and articulate a worldview, this view suggests that competing groups do not need to engage in a fully constructive dialogue in order to produce science”. This challenges my original response to the blockchain discussion to assume that a solution would be an in-person dialogue. Thus, pushing the response for this capstone project topic of technology companies in cities to strive beyond engaging a tech company CEO and an urban planner, though that could support the overall exploration, and to look for other means of collaboration beyond theory debate.
  <br></br><br></br>Furthermore, this capstone proposes data as a source of prompting future collaboration.  Cathy O Neil’s Weapons of Math Destruction dissects the way that artificial intelligence algorithms expose human biases both in the data being used to train these algorithms and the design of the algorithm themselves. Demanding transparency of the algorithm design and the data itself is one of the unique features of artificial intelligence that has a lot of potential to force societies to reflect on  the innate biases that shape our world today. Despite the absence of machine learning or artificial intelligence in this study, those technologies are proposed in the “future plans” section and the O’neil’s same logic of transparency still applies. 
  <br></br><br></br>Data is a language used heavily by urban planners in geolocation mapping, demographic research, housing location and pricing, and multitudes of other subjects. Technology companies are often building the technology that urban planners and countless other experts and individuals use. This is one of the main reasons that data seems like an appropriate tool to help the two disciplines start a new collaborative conversation. Because this capstone is aimed to test whether data can similarly expose points of semantic intersection and contention between or within urban studies and technology businesses, it will be important to analyze the text as data with the framework that there should be as little bias as possible, and in the future, bringing in experts to confirm that the results of the data are not being represented as a means of securing a hypothesis, instead as evidence of whatever outcome.  
<br></br><br></br>In an older philosophical publication in the Sociological Review about the demarcation of science from non-science, “boundary work” is defined as a rhetorical style used for describing science for the public or creating distancing between experts typically by experts. Interdisciplinarity and boundary work both have elements of rhetorical accentuation as well as similar strategic methods of legitimation of one’s own work. 
The logics of interdisciplinarity project conducted an 18-month study on the fields of environmental and climate change research, ethnography in the IT industry, and art-science. They chose these three interdisciplinary subjects because they are each fields that stem from the sciences or engineering departments and social sciences, humanities or art departments. The project is focused on the context of contemporary interdisciplinarity as relating to the relationship between science, technology, and society. There is a heightened use of interdisciplinary rhetoric from governments, funders, and researchers using mainly accountability logic. Accountability logic within interdisciplinarity can serve as a form of aid to propose solutions to questions proposed by the public or another discipline.  Barry sees the logic of innovation within interdisciplinarity most commonly in ethnography in the IT industry with consumer products. However, this is often applied as a method of making a case for strategic technology-investments and not user driven applications. Thus, the logics of accountability and innovation within interdisciplinarity must be considered before and during the process of engaging the cross-discipline discourse between city planning and technology businesses in this study. 
<br></br><br></br>Collective Intelligence
<br></br><br></br>Collective intelligence (CI) is a key tool that can be used for improving problem-solving in the public sphere. Similar to artificial intelligence, collective intelligence does not have a clear-cut, universal definition. For the purpose of analyzing the use of collective intelligence in later case examples, it is useful to look at collective intelligence from the lens of social science.  
<br></br><br></br>Nesta Ceo and Collective Intelligence Expert, Geoff Mulgan describes collective intelligence as, “The ability of large groups - a community, region, city or nation - to think and act intelligently in a way that amounts to more than the sum of their parts. It depends on observation, attention, analysis, creation, memory, and judgement”  
<br></br><br></br>In the Prologue Democratic Reason: Politics, Collective Intelligence, and the Rule of the Many, political scientist Hélène Landemore claims,  “Simmering in Ségolène Royal’s discourse was the notion of collective intelligence-the idea that political solutions are often best figured out by that people as a whole, when individuals talk to each other and contribute their bits of knowledge to a general public discussion”.  Later on Landemore writes, “Collective distributed intelligence in politics may thus span a vast array of institutions, all of which might be needed to constrain, guide, and even correct citizens’ individual mental operations”.
<br></br><br></br>French philosopher and media scholar, Pierre Levy and the journal editors of On Collective Intelligence in Advances in Intelligence and Soft Computing have similar definitions. First Levy gives his definition in 1997 in the context of the beginning of the emergence of computers, “A form of universally distributed intelligence, constantly enhanced, coordinated in real time, and resulting in the effective mobilization of skills”. This definition parallels Henrik Ickler’s point almost fifteen years later that, “In the context of Web 2.0, Collective Intelligence is a general term for user participation and the resulting added value”. 
<br></br><br></br>Founding director of the MIT Center for Collective Intelligence and author of Handbook Of Collective Intelligence, Thomas Malone summarizes CI precisely as, “Groups of individuals acting collectively in ways that seem intelligent”. Alternatively, more expansive descriptions such as, “A phenomenon according to which the purposeful interaction between individuals creates intelligent solutions and behaviors that might not have come to existence without this concerted effort of a community. The members of such communities form a social network, typically over the internet. They are engaged with each other over a sustained period of time to develop an area of innovation through collaboration and exchange of ideas, experiences, and information. 
<br></br><br></br>After synthesis of multiple definitions of scholars in the fields of CI, political theory, and sociology, collective intelligence can be defined here as the ability for collaboration between groups (or individuals) to share separate information, resulting in the creation of new information and/or solutions. This definition is not a standard, universal definition, but helps clarify CI for the purpose of this capstone, especially for the purpose of the method, as well as to reinforce the concept of “knowledge clusters” later on. Though Landemore closely identifies democratic reason with collective intelligence, it is left out of the definition because collective intelligence does not necessarily include a majority population included in decision-making. Wikipedia, which many collective intelligence writers use, can include simply the “expertise” of two individuals to create a public page about a topic. It can simply include connecting the information or knowledge of two or more separate groups to create a resulting new kind of information and insight. Here, CI is applied in the hypothesis as connecting the information or knowledge of urban planners and technology businesses to improve city planning, innovation, and introducing innovation into the city. Some of the vocabulary used in this collection of definitions such as “communicating”, “exchange”, and “acting together” is condensed into the ideas of “collaboration” and “shared”.
<br></br><br></br>Public and Private in Cities
<br></br><br></br>There is a long history of the ways in which cities are designed. This project is looking at case studies across the world within the last twenty years, thus, the focus is less on the history of city design, and more on the role of public and private entities in new town creation or urban renewal development. Ebenezer Howard, one of the most influential urban planners proposed his “Garden City” in the 1980’s. The “Garden City” was to provide parks and areas to play, all sorts of businesses for gathering. The industrial revolution and the “small scale neighborhood” model was exported outside the UK into Europe, and the U.S. in places such as Jackson Heights, Queens. Following, was the rise of Neoliberalism in the 1970’s, largely coinciding with mismanagement of encapsulated Fordist systems in the U.S. and U.K . A key part of neoliberalism is the entrance into the global market. As globalization started to spread, the welfare state and garden cities transformed into neoliberal skyscrapers. Following this rapid transition at the end of the twentieth century, Jane Jacobs most famously wrote, “Cities have the capability of providing something for everybody, only because, and only when, they are created by everybody”. As smart cities rise and technology companies spread, they have posed a threat to urban theorists and planners for fear of techno-cratic control as opposed to democratic construction of cities. 
<br></br><br></br>Today, many national governments have been partnering with large technology companies for years. The United States Government works with the companies including the “big five”: Amazon, Apple, Google, Facebook, Microsoft, not including others such as IBM, CISCO, and more. This blurred public and private control of cities is additional evidence to support the proposed question of whether technology, here text analysis, can offer a method of starting interdisciplinary communication. This method could offer some solutions to the changing role of technology companies in cities. 
<br></br><br></br>In this paper, computer science journals are grouped with business technology publications. Though very different areas, both are being summarized by the larger actor of private companies or corporations in this sense. In discussing big technology in the urban planning context and vise versa, one of the main points of distinction is with the role of status being public or private. 
</p>
  </div>
  <div id="method">
  <p>Method Background</p>
  <img src= "https://i.ibb.co/dLcpvLM/JMJ4021.jpg" height = "300" width = "500" />
  <p>In order to delve into the discussion of large technology companies' presence in cities, this study looks at ten articles. For the purpose of this analysis,  two categories are used to divide the ten articles. One category will be summarized by “urban”. The initial idea was to compare and contrast the semantic discussion on big technology companies coming into cities. Originally inspired by Amazon HQ2 in New York City,  the search began specifically with the big technology companies, but there were surprisingly few “urban studies” journal articles or conference papers that focused on specific company geo-locations. It became even more complicated to find articles that were compatible with the software as well as articles that acted as the cross-disciplinary equivalent of each respective case. In searching for the most “observably similar” articles and conference materials by their abstracts, keywords, and skimming, it became clear that it was much more difficult to find exactly the same subject reviewed by the two different discipline experts. Thus the articles are not all focused on one case study but more a focus within four larger nations: Korea, India, Poland, the United States. 
  <br></br><br></br>Within the four geographical regions, this project focuses on modern technology companies that come after the beginning of the development of the World Wide Web in 1991 and the industrial sector including digital technology companies that have started emerging within cities in the past fifteen years. The digital revolution started in the 1980’s, and some of the articles refer to history before the Internet Age, but all were published after 2005 in order to narrow the scope. 
  <br></br><br></br>In the “urban” category, articles included are from the European Planning Studies journal, Sustainable Cities and Society, two articles from Cities, and the Regional Studies, Regional Science journal. In no way do these five articles represent the “urban studies” field as a whole. Some of these journals may not be considered under the discipline of “urban studies”, but they were all found either under “Sustainable Urban Environments: Journals, Databases & E-books” or under the “Urban Planning” section of the NYU Libraries Research Guides. 
  <br></br><br></br>The second category is referred to as “tech”. The “tech” publications are from the 2017 IEEE Technology & Engineering Management Conference (TEMSCON), Perspectives on Global Development and Technology, EAST-WEST Journal of Economics and Business, Thunderbird International Business Review, and an article in Business Wire directly from Amazon. In the same way that the sources in “urban” don’t just represent “urban studies”, the conference materials and articles under the “tech” category do not only fall under the category of the “tech industry”. This category eencompasses both business journals as well as technology conference materials found under the “Technology” or “Business” subjects in the NYU Libraries Research Guide, or in the “Computer Science Research”. “Technology”, “Business”, and “Computer Science” may be separate disciplines with overlap, but overall is not writing from the lens of urban, city, or regional studies. All works are cited in the bibliography following the conclusion. 
<br></br><br></br>QUANTITATIVE METHOD
<br></br><br></br>
<img src="https://i.ibb.co/NW9TgFX/Top-Word-Frequency-by-Category.png"></img>
<br></br><br></br>Column Chart 1. Made using ATLAS.ti and visualized in Google charts. 
<br></br><br></br>The first text scraping of the ten articles is of the top twenty  most frequent words used excluding STOP words such as “and”. Column Chart 1 displays the top twenty most frequent words from the combined  “tech” and  “urban” documents and then additionally shows the individual numbers for the “tech” and “urban” categories for those terms, also excluding STOP words.. Below in Column Charts 2 and 3 are the top twenty most frequent words in the corresponding “tech” and “urban” categories. 
<br></br><br></br>
<img src="https://i.ibb.co/31z7NQK/City.png" ></img>
<br></br><br></br> Column Chart 2. Made using ATLAS.ti and visualized in Google charts.
<img src="https://i.ibb.co/8NJLYNj/Tech.png" ></img>
<br></br><br></br>Column Chart 3. Made using ATLAS.ti and visualized in Google charts.
<img src="https://i.ibb.co/0JBXc1g/Screen-Shot-2020-05-15-at-6-17-25-PM.png" ></img>
<br></br><br></br>Keyword Connections and Themes Visualization. Made in ATLAS.ti.
<br></br><br></br>Above is the Keyword Connections and Themes Visualization. This mapped all the keywords provided in the ten articles excluding location specific terms such as “Hydeerbad”.. Two variations include the keywords for the article, “The Role of Geographic Location in the Acquisition Strategies of High-Technology Firms: Evidence from Computer Networking Equipment Industry” are sourced from EBSCO, noted next to each term, because the authors did not provide their own key terms. The other variation is that the Amazon release, “Amazon Selects New York City and Northern Virginia for New Headquarters” does not have any key terms. The left side shows the connection of the “city” articles to their respective key terms, and the right side the “tech” term connections. In the middle are three common themes of “business/industry”, “cluster”, “innovation”, “planning”, and “knowledge”. On the left hand side, there is one additional theme of “cities”, which also includes “city”. Other key terms that did not have direct common repetition were grouped respectively based on their relations within the articles on the side of the category of article they came from. 
<img src="https://i.ibb.co/m8rY8Sc/Screen-Shot-2020-05-15-at-12-28-29-PM.png" ></img>
<br></br><br></br>Article References Table. Made in ATLAS.ti, exported to Microsoft Excel. 
<br></br><br></br>Using ATLAS.ti, all the references cited in all ten articles were exported into a spreadsheet. Above is the condensed list of references that were listed across multiple articles. 35 total references overlap within and across the “tech” and “urban” categories. Five total authors were cited twice in the “tech” category. Six total authors were cited twice in the “urban” category. Eight total authors were cited across both disciplines at least once including four authors that were also cited twice within their category in addition to being cited across two categories. 
Referring to Article References Table 1. Of the five pairs of “tech” and “urban” publications in their respective regions, only the articles about tech clusters in Korea overlap with Nelson and Lundvall, and Porter. 
</p>
  </div>

  <div id="analysis">
  <p>Method Analysis</p>
  <img src= "https://i.ibb.co/BPrgF0B/JMJ4017.jpg" height = "300" width = "500" />
  <p>Column Charts 2 and 3 showed a 50% overlap between the “tech” and “city” categories’ top twenty most frequently used. Some related to public sector activities such as “government” “local” and “state” were exclusive to the “city” category. Similarly, one might also identify  terms such as “firm”, “capacity”, and “business” that were exclusive to the “tech” category’s top twenty terms as typically private business terminology. Yet, with a 50% overlap, one might be able to use these visualizations as a jumping off point to lead into discussions about diverging subject focuses such as the structural implications on business and government when individuals or groups of firms move into cities. 
	<br></br><br></br>In the Keyword Connections and Themes Visualization on page 17, it could be brought to attention that keywords including the term “cluster” have an equal amount of key terms. It would also be interesting to look at the number of geographical terms used in both categories. The keyword “regional innovative clusters” is used on the “tech” side, but the city side uses the term “regional innovation”. Both areas discuss the “regional” importance of “knowledge clusters’. Primarily, in the documents ``The Role of Geographic Location in the Acquisition Strategies of High-Technology Firms: Evidence from the Computer Networking Equipment Industry” under the “tech” category. This article used Cisco Systems as a case study on the role of  geographic location, patents, and international organizational networks, and other connectivity mechanisms for high-technology investments.  
	<br></br><br></br>There were  well over 100 references cited in the ten sources selected as topics intended to be discussing the same topic of technology companies presence in cities, yet surprisingly only eight cross-disciplinary referenced authors and fourteen disciplinary overlapping authors. The urban studies articles about high-tech clusters in  Hyderabad and North Texas and California follow a similar academic structure of going through the history, geography, and demography, accessibility, and sustainability of the high-tech locations.  The other three “urban” articles focus more generally on the role of governments, innovation policies, clusters on current structures. Then, with the “tech” resources, there is a heavier discussion on the role of “knowledge cluster”. Excluding the Amazon publication which didn’t provide a lot the analysis given its short length, a lot of the focus of the “tech” articles was on the economic effects of “clustering” and the evolution of “innovation” within the technology manufacturing industries. The other primary focus was on the role of “knowledge clusters” which was additionally expanded on the “city” case study in Poland. 
  <br></br><br></br>The “tech” article,  “Structure and significance of knowledge networks in low-tech clusters in Poland” studies the role of physical proximity of “knowledge” and “innovation” clusters on the quality and quantity  of the knowledge and innovation created. Though these common terms such as “knowledge”, “innovation”, “cluster”, “tech”, etcetera may seem broad and arbitrary, this article uses them to make an almost “meta” point here about the role in creating collective intelligence. Abbasiharofteh and Dyba use a case study of furniture clusters in Poland to study the role of clusters in creating international connection and local collective intelligence. Though this is focused locally on low-tech firms, the “tech” article for South Korea makes a very similar argument for regional innovation as well. The societal conception of these technology businesses is that they have nothing to do with the physical world, and that cities have everything to do with the physical world. Technology companies are often thought of in waves and machines, and cities as the streets and buildings. Yet, as these two articles point out, the information they collect can have a collective benefit on the citizens in the place, the public, and private entities, as well as global firms and citizens that are connected to the physical headquarters or development centers of these firms in a less physical manner. The way in which local knowledge is created whether that be between firms in clusters, between citizens, governments, or between the three can increase the level of innovation and integrative synthesis interdisciplinarity. Using these broader terms and  presence or  lack of overlapping referencing in this study can help facilitate that process. 
  <br></br><br></br>To conclude this larger analysis, the search for the 10 articles as well as within the text analysis of the selected cases recognized  patterns of terminology such as industrial clusters, big technology, high technology, tech clusters, etc… that seem to have different standards across the four computer science journals as well as across the overall tech sector. This is a natural inconsistency that exists within any field and cannot be completely addressed through data analysis. Certainly this will continue to exist, very prominently in the field of modern technology. For example, “Artificial Intelligence” and “Machine Learning” have such wildly varying definitions, which is why they are often used by companies, governments, individuals, across the board, as a mechanism for “hype” and sometimes confusion as a distancing mechanism for strategic investment agendas. 
	<br></br><br></br>Though there were flaws in the construction of variables and the technical execution of the data analysis, I argue that the simple word crunching  identified above suggests that there is potential for communicating an opportunity for interdisciplinarity between the urban planning and technology business sector regarding the topic of technology firms locating to cities. 
</p>
  </div>

  <div id="future">
  <p>Future Plans</p>
  <img src= "https://i.ibb.co/YhfwP7P/JMJ4029.jpg" height = "300" width = "500" />
  <p>This capstone is very much an ongoing project. Due to challenges during the time of the COVID-19 Crisis, the technical execution is limited to very simple qualitative data and analysis. More time to work with the text as data with access to the full version of ATLAS.ti would allow for further analysis of how to present this data to experts. The visualizations are also very simple and could be presented in a simpler formatting with future development. 
  <br></br><br></br>In addition, This study primarily stays within Academia with all but the Amazon release papers from academic journals and conference materials. Originally, there was to be an additional text analysis of Twitter data. In the next phase of this project, I would like to use a model that my peer is building to trace the Covid-19 crisis for twitter scraping urban studies scholars and technology companies and computer science scholars. <br></br><br></br>One next step will be using a twitter developer account to do some sentiment analysis. Starting in June of 2019, Twitter removed its geo data collection from individual tweets and thus developers can only collect data from individual profile location data which is a much slower, and a more complicated process. In addition, tweets can only be used as data within fourteen days of being published, which also made it rather difficult to obtain twitter data to use sentiment analysis in the first place. Thus, in the future it will be important to scope out an event of big technology companies going into a particular city to focus on twitter data collection before the data analysis. 
  <br></br><br></br>Similarly, due to the time constraint this experiment used ATLAS.ti, a simple software to do very minimal text scraping, but in the future, it would be useful to not only text scrape, but also use an algorithm that can learn from the text and search for similar text as well as create a speculative design project for predicting which discipline a piece of writing originates. There are many opportunities to be creative with the data analysis and machine learning processes in the future. The purpose of this study was not to test out new methods of data analysis, but to instead narrow in on two disciplines, one topic, and identify, if any, elementary connections or miscommunications could be distinguished in the results.  
  <br></br><br></br>Another possible suggestion would be to focus on particular technology corporations as case studies. Consequently though, the original idea of using the large technology firms headquarters  such as Amazon, Apple, and Google, may have been more difficult to do this exact analysis with, given that the Amazon press release had no key terms and was the shortest document. However, if the sources were available, the text analysis method could possibly be adjusted to accommodate a lack of key terms or shorter length document. 
  <br></br><br></br>As mentioned in the method, it became more time consuming to find the “perfect” articles in both disciplines. Much of this experiment was not fulfilled to the point of drawing strong conclusions, however as stated in the analysis it has shown evidence for the potential of success with iteration. 
  <br></br><br></br>In the future, the same experiment could use articles with at least one or multiple common keywords either determined by the author, the journal, or database, that the article or conference paper is published in. In addition, adding that and some other variables to  determine a criteria for a pair disciplinary “equivalent” papers. This would help solidify some conclusions one would be able to draw in semantic hyperlinking and resulting miscommunicated terms, or canonized terms. 
</p>
  </div>

<div id="conclusions">
<p>Conclusions</p>
<p>As technocratic influence starts to become a rapidly increasing trend in new city development, urban renewal, and restructuring, communication between the public and private sectors, urban planners and technology companies, will become extremely vital to the improvement of lives in cities. Smart cities are embedding technology into the urban infrastructure. Older cities are introducing physical firms of big technology companies. Overall, increased government and technology company collaboration and power transfer now warrant a reevaluation of how these entities are sharing or transferring decision-making power. There is already plentiful literature reevaluating state development starting during the transition of new cities shifting from the “welfare city” to “neoliberal cities” and in the past fifteen years as technocratic influence has increased in new “smart cities”. This interdisciplinary analysis is a tool in the larger discussion of the new role of private technology firms in state development of cities.  
<br></br><br></br>To conclude, the goal in mind for this capstone project was to try to see if text as data could be used as a tool to help facilitate a starting point for cross-discipline collaboration. In this case, if urban planning literature and big technology sources could better understand the perspective of the other on the subject of large technology companies physically moving into cities. Due to the circumstances, the technical aspect was not carried out at a very high level, and in the future twitter analytics would be helpful as well as additional advanced machine learning methods. However, through word crunching of frequent words, keywords, and sources of the ten articles, the offering of display of overlapping theme words, lack of overlapping cited sources offers a possible solution for the very beginnings of subordinated service interdisciplinarity between urban planning and big tech companies on the subject of of physical tech clustering. Within the topic of knowledge clusters themselves, both the “tech” articles and the “city” articles identify the possible benefits of knowledge creation through innovative clustering. The disciplines may consider different possible problems such as the specific regional location and the economic status of that zone from the “tech” side and the influence of clusters on transportation on the “urban” side as seen in the second graph. Yet, identifying the “innovative cluster” with text as data offers a starting point to discussing these two diverging points. With continued development, I believe the concept of increasing effective interdisciplinarity through technology can be developed further within the fields of urban planning and technology companies and many other disciplines.
</p>
</div>

<div id="references">
  <p>Bibliography</p>
  <p>Abbasiharofteh, Milad, and Wojciech Dyba. “Structure and Significance of Knowledge Networks in Two Low-Tech Clusters in Poland.” Regional Studies, Regional Science 5, no. 1 (January 2018): 108–16. https://doi.org/10.1080/21681376.2018.1442244.

Amazon. “Amazon Selects New York City and Northern Virginia for New Headquarters” Business Wire (November 2018). https://www.businesswire.com/news/home/20181113005798/en/Amazon-Selects-New-York-City-Northern-Virginia

Arogyaswamy, Bernard, Lemoyne College, and Alojzy Nowak. “HIGH TECH AND SOCIETAL INNOVATION IN POLAND: PROSPECTS AND STRATEGIES,” n.d., 27.

Barry, Andrew, Georgina Born, and Gisa Weszkalnys “Logics of Interdisciplinarity” Economy and Society, Vol. 37, No. 1, (January 2008): 20-49., DOI: 10.1080/03085140701760841

Bastiaens, Theo J. Baumöl, Ulrike. Krämer, Bernd J. “On Collective Intelligence, Advances in Intelligent and Soft Computing” On Collective Intelligence (2011). https://www.springer.com/gp/book/9783642144806

Das, Diganta. “Hyderabad: Visioning, Restructuring and Making of a High-Tech City.” Cities 43 (March 2015): 48–58. https://doi.org/10.1016/j.cities.2014.11.008.

Deepak, C., and M.H. Bala Subrahmanya. “Exploring the Influence of Absorptive Capacity on Innovation in Bengaluru High-Tech Manufacturing Cluster.” In 2017 IEEE Technology & Engineering Management Conference (TEMSCON), 166–72. Santa Clara, CA: IEEE, 2017. https://doi.org/10.1109/TEMSCON.2017.7998372.

Gieryn F, Thomas. “Boundary-Work and the Demarcation of Science from Non-Science: Strains and Interests in Professional Ideologies of Scientists”, American Sociological Review, Vol. 48, No. 6, (December 1983): 781–795. https://www.jstor.org/stable/2095325?seq=1

The Governance Lab, http://www.thegovlab.org, Accessed February 1, 2020.

Howard, Ebenezer, and Frederic J. Osborn. Garden Cities of To-Morrow. London: Faber and Faber. (1946): 168  //catalog.hathitrust.org/Record/000648683.

Ickler, Henrik.  “On Collective Intelligence, Advances in Intelligent and Soft Computing”  On Collective Intelligence https://link.springer.com/content/pdf/10.1007%2F978-3-642-14481-3.pdf 

Jacobs, Jane. The Death and Life of Great American Cities. xxxvi, New York: Modern Library, (2011): 312 //catalog.hathitrust.org/Record/011251037.

Jessop, Bob, Liberalism, Neoliberalism, and Urban Governance: A State- Theoretical Perspective. Antipode, 34(3),  (2002): 452-472 https://onlinelibrary.wiley.com/doi/pdf/10.1111/1467-8330.00250?casa_token=aII_N85Y5RkAAAAA:Mf_okBX2c7gtHSeTMAEFv-Df1Ij5rZHosZDTGWMZhV6V_OOp1yV7zLjHxpCbLn4xlGNH48qXcaEe

Kasinitz, Philip, Mohamad Bazzi, and Randal Doane. "Chapter 8: Jackson Heights, New York." Cityscape 4, no. 2 (1998): 161-77. Accessed May 16, 2020. www.jstor.org/stable/41486481.

Landemore, Helene. “Democratic Reason: Politics, Collective Intelligence, and the Rule of the Many.” (2012) https://press.princeton.edu/titles/9907.html

Lee, Kongrae. “Circulative Linkages of Regional Knowledge Activities: Empirical Evidence from the Korean Case.” Perspectives on Global Development and Technology 2, no. 2 (2003): 237–54. https://doi.org/10.1163/156915003322763575.

Lee, Sam Youl, Meansun Noh, and Ji Yung Seul. “Government-Led Regional Innovation: A Case of ‘Pangyo’ IT Cluster of South Korea.” European Planning Studies 25, no. 5 (May 4, 2017): 848–66. https://doi.org/10.1080/09654313.2017.1282084.

Levy, Pierre. “Collective Intelligence: Mankind's Emerging World in Cyberspace, Perseus Books.” (1997) https://dl.acm.org/citation.cfm?id=550283

Malone, Thomas. Laubacher, Robert. Dellarocas, Chrysanthos  “Harnessing Crowds: Mapping the Genome of Collective Intelligence” MIT Sloan Research Paper No. 4732-09. (February 2009). http://dx.doi.org/10.2139/ssrn.1381502

Mazzei, Michael.“Computer Revolution.” Salem Press Encyclopedia. (2019). http://search.ebscohost.com.proxy.library.nyu.edu/login.aspx?direct=true&db=ers&AN=98402048&site=eds-live.

O'Neil, Cathy. Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy. First edition. New York: Crown, 2016.
“Professor Andrew Barry.” UCL Department of Geography, 2019, www.geog.ucl.ac.uk/people/academic-staff/andrew-barry.
Rebentisch, Hannah, Caroline Thompson, Laurence Côté-Roy, and Sarah Moser. “Unicorn Planning: Lessons from the Rise and Fall of an American ‘Smart’ Mega-Development.” Cities 101 (June 2020): 102686. https://doi.org/10.1016/j.cities.2020.102686.

Saunders, Tom. Mulgan, Geoff.  “Governing with Collective Intelligence.” Nesta UK, 2017 https://undg.org/wp-content/uploads/2017/04/governing_with_collective_intelligence.pdf

Shelton, Taylor & Zook, Matthew & Wiig, Alan. “The 'actually existing smart city'”. Cambridge Journal of Regions, Economy and Society. (2014): 8. 13-25. 10.1093/cjres/rsu026. 

Verdict “The History of Smart Cities: Timeline” Verdict (February 2020). (https://www.verdict.co.uk/smart-cities-timeline/ Accessed March 1, 2020

Yurov, Kirill M., Shane M. Greenstein, Mark T. Shanley, and Richard E. Potter. “The Role of Geographic Location in the Acquisition Strategies of High-Technology Firms: Evidence from Computer Networking Equipment Industry.” Thunderbird International Business Review 55, no. 4 (July 2013): 371–85. https://doi.org/10.1002/tie.21551.

Zandiatashbar, Ahoura, Shima Hamidi, and Nicole Foster. “High-Tech Business Location, Transportation Accessibility, and Implications for Sustainability: Evaluating the Differences between High-Tech Specializations Using Empirical Evidence from U.S. Booming Regions.” Sustainable Cities and Society 50 (October 2019): 101648. https://doi.org/10.1016/j.scs.2019.101648.</p>
</div>

</div></div>

  )


}

export default App;
